export default function Prisma1InstallationAndSetup() {
    return (
        <div>
            <h1>Installation and Setup</h1>

            <div>
                <h2>Installation</h2>
                <p>Install Prisma:</p>
                <pre><code>
{`</> Bash
npm i prisma --save-dev
`}
                </code></pre>

                <p>Then initialize Prisma</p>
                <pre><code>
{`</> Bash
npx prisma init --datasource-provider sqlite
`}
                </code></pre>
                <p>The command <code>npx prisma init</code> creates <code>.env</code>, <code>schema.prisma</code>, and <code>prisma.config.ts</code> files.</p>
                <p>Meanwhile <code>--datasource-provider sqlite</code> wrote to use sqlite that otherwise using postgresql on default.</p>

                <p>In <code>schema.prisma</code>:</p>
                <pre><code>
{`// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Get a free hosted Postgres database in seconds: ${"`npx create-db`"}

generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
}

datasource db {
  provider = "sqlite"
  url = env("DATABASE_URL")
}
`}
                </code></pre>
                
                <p>In <code>.env</code>:</p>
                <pre><code>
{`# Environment variables declared in this file are NOT automatically loaded by Prisma.
# Please add ${'`import "dotenv/config";` to your `prisma.config.ts`'} file, or use the Prisma CLI with Bun
# to load environment variables from .env files: https://pris.ly/prisma-config-env-vars.

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB and CockroachDB.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

DATABASE_URL="file:./dev.db"`}
                </code></pre>

                <p>In <code>prisma.config.ts</code>:</p>
                <pre><code>
{`</> TypeScript
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`}
                </code></pre>
            </div>
            <hr className="--hr-faded" />

            <div>
              <h2>Dependency Installation Notes</h2>
              <p>Varies by the database choice.</p>

              <h3>Prisma v7 &mdash; what to install per project</h3>
              <table>
                <thead>
                  <tr>
                    <th>Package</th>
                    <th>Install Command</th>
                    <th>Notes</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td colSpan={3}>
                      ALWAYS REQUIRED &mdash; EVERY PROJECT, EVERY DATABASE
                    </td>
                  </tr>
                  <tr>
                    <td>All</td>
                    <td>
                      <pre><code>
{`npm install @prisma/client
npm install --save-dev prisma`}
                      </code></pre>
                    </td>
                    <td><code>prisma</code> is the CLI. <code>@prisma/client</code> is what the app imports at runtime.</td>
                  </tr>

                  <tr>
                    <td colSpan={3}>
                      THEN ADD DRIVER ADAPTER &mdash; PICK BASED ON THE DATABASE
                    </td>
                  </tr>
                  <tr>
                    <td>SQLite (Node.js)</td>
                    <td>
                      <pre><code>
{`npm install @prisma/adapter-better-sqlite3
npm install --save-dev @types/better-sqlite3`}
                      </code></pre>
                    </td>
                    <td>The <code>@types</code> package is needed for Typescript to recognise the adapter.</td>
                  </tr>
                  <tr>
                    <td>SQLite (Bun/Turso)</td>
                    <td>
                      <pre><code>
{`npm install @prisma/adapter-libsql`}
                      </code></pre>
                    </td>
                    <td>Use this instead when running under Bun or Turso as hosted SQLite.</td>
                  </tr>
                  <tr>
                    <td>PostgreSQL</td>
                    <td>
                      <pre><code>
{`npm install @prisma/adapter-pg pg
npm install --save-dev @types/pg`}
                      </code></pre>
                    </td>
                    <td>Works with any Postgres host &mdash; Supabase, Neon, Railway, local Docker, etc.</td>
                  </tr>
                  <tr>
                    <td>MySQL</td>
                    <td>
                      <pre><code>
{`npm install @prisma/adapter-mariadb`}
                      </code></pre>
                    </td>
                    <td>Works with MySQL, PlanetScale and TiDB</td>
                  </tr>
                  <tr>
                    <td>Cloudflare D1</td>
                    <td>
                      <pre><code>
{`npm install @prisma/adapter-d1`}
                      </code></pre>
                    </td>
                    <td>SQLite at the edge inside Cloudflare Workers. D1 binding is passed directly &mdash; no connection string.</td>
                  </tr>

                  <tr>
                    <td colSpan={3}>
                      AFTER INSTALLING &mdash; ALWAYS RUN THIS
                    </td>
                  </tr>
                  <tr>
                    <td>All</td>
                    <td>
                      <pre><code>
{`npx prisma generate`}
                      </code></pre>
                    </td>
                    <td>Generates the client into your <code>output</code> folder based on your schema. Re-run this every time you change <code>schema.prisma</code>.</td>
                  </tr>
                </tbody>
              </table>
            </div>
        </div>
    )
}